In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("Motor Trend Car Road Tests.xlsx")

# EDA

In [4]:
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [5]:
df.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   model   32 non-null     object
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64
 9   am      32 non-null     int64
 10  gear    32 non-null     int64
 11  carb    32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

# Nulos y duplicados

# Train / Test

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X = df.drop(columns = ["model", "mpg"])
y = df['mpg']

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4)

# Escalamiento de variables

In [35]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(X_train)

X_scaled_train = scaler.transform(X_train)

X_scaled_test = scaler.transform(X_test)

# Modelo

In [38]:

import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
import statsmodels.api as sm

# Agregar constante para el término independiente
X_scaled_train_const = sm.add_constant(X_scaled_train)
X_scaled_test_const = sm.add_constant(X_scaled_test)

In [40]:
# Modelo train
modelo_train = sm.OLS(y_train, X_scaled_train_const).fit()

modelo_train.summary()

C:\Users\juanm\anaconda3\Lib\site-packages\scipy\stats\_axis_nan_policy.py:531: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=19
  res = hypotest_fun_out(*samples, **kwds)

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.885
Model:                            OLS   Adj. R-squared:                  0.741
Method:                 Least Squares   F-statistic:                     6.144
Date:                Mon, 08 Sep 2025   Prob (F-statistic):            0.00840
Time:                        17:50:30   Log-Likelihood:                -41.976
No. Observations:                  19   AIC:                             106.0
Df Residuals:                       8   BIC:                             116.3
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         20.1000      0.779     25.793      0.000      18.303      21.897
x1             1.3063      3.727      0.350      0.735      -7.289       9.902
x2             1.4946      4.434      0.337      0.745      -8.730      11.719
x3            -3.7383      4.397     -0.850      0.420     -13.877       6.400
x4             1.4610      2.307      0.633      0.544      -3.858       6.780
x5            -5.0821      3.440     -1.478      0.178     -13.014       2.850
x6             3.0381      2.323      1.308      0.227      -2.318       8.394
x7            -1.4278      1.893     -0.754      0.472      -5.794       2.938
x8             2.2828      1.937      1.178      0.273      -2.185       6.750
x9            -1.8096      2.507     -0.722      0.491      -7.591       3.972
x10            1.9146      3.430      0.558      0.592      -5.995       9.824
==============================================================================
Omnibus:                        4.228   Durbin-Watson:                   1.791
Prob(Omnibus):                  0.121   Jarque-Bera (JB):                1.852
Skew:                           0.428   Prob(JB):                        0.396
Kurtosis:                       1.732   Cond. No.                         22.2
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [42]:
# 7. Evaluación del modelo entrenado con TRAIN en TEST

y_pred = modelo_train.predict(X_scaled_test_const)

r2 = r2_score(y_test, y_pred)

print(f"R²: {r2:.4f}")

R²: 0.4075